# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 16:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('planb', '0002_hostconfig_add_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostconfig',
            name='backup_size_mb',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Estimated total backup size in MiB.', verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='hostconfig',
            name='date_complete',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 2, 0, 0, tzinfo=utc), verbose_name='Complete date'),
        ),
        migrations.AlterField(
            model_name='hostconfig',
            name='description',
            field=models.TextField(blank=True, help_text='Quick description/tips. Use the first line for labels/tags.'),
        ),
        migrations.AlterField(
            model_name='hostconfig',
            name='friendly_name',
            field=models.CharField(help_text='Short name, should be unique per host group.', max_length=63, unique=True, verbose_name='Name'),
        ),
    ]
