# Generated by Django 2.0.2 on 2018-02-19 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planb', '0005_add_backuprun'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostgroup',
            name='last_monthly_report',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostconfig',
            name='hostgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hostconfigs', to='planb.HostGroup'),
        ),
    ]
