# Generated by Django 2.0.2 on 2018-04-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planb', '0007_first_and_last_fail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostconfig',
            old_name='complete_duration',
            new_name='average_duration',
        ),
        migrations.AlterField(
            model_name='hostconfig',
            name='average_duration',
            field=models.PositiveIntegerField(default=0, help_text='Average duration of succesful jobs in seconds.', verbose_name='Time'),
        ),
    ]
