# Generated by Django 2.0.2 on 2018-04-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planb', '0008_average_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostconfig',
            old_name='backup_size_mb',
            new_name='total_size_mb',
        ),
    ]
