# Generated by Django 2.0.4 on 2019-06-06 13:10

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('planb', '0010_drop_keep_booleans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HostConfig',
            new_name='Fileset',
        ),
    ]
