# Generated by Django PlanB 1.6.post1+263.g079027b.dirty (Django 3.2.8) on 2022-03-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planb', '0019_add_fileset_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuprun',
            name='snapshot_name',
            field=models.CharField(blank=True, help_text='Custom snapshot name; will not be auto-deleted if set', max_length=30),
        ),
    ]
