# Generated by Django PlanB 1.7 (Django 3.0.6) on 2020-05-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_exec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='can_create_snapshot',
            field=models.BooleanField(default=False, help_text='When checked the transport will create the snapshots.', verbose_name='Can create snapshot'),
        ),
        migrations.AddField(
            model_name='config',
            name='can_rotate_snapshot',
            field=models.BooleanField(default=False, help_text='When checked the transport will rotate the snapshots.', verbose_name='Can rotate snapshot'),
        ),
    ]
