# Generated by Django 2.0.4 on 2019-06-07 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport_rsync', '0002_import_fileset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='fileset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='planb.Fileset'),
        ),
    ]
