# Generated by Django PlanB 1.6.post1 (Django 2.1.9) on 2021-07-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_rsync', '0004_auto_20200512_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='flags',
            field=models.CharField(blank=True, default='', help_text='Default "", add "--no-perms --chmod=D0700,F600" for (windows) hosts without permission bits, add "--iconv=utf8,latin1" for hosts with files with legacy (Latin-1) encoding, add "--bwlimit=" for hosts with no bandwidth limit, add "--compress-choice=lz4" for newer compression.', max_length=511),
        ),
    ]
