# Generated by Django PlanB 1.7 (Django 3.2.16) on 2023-09-13 12:34

from django.db import migrations, models
import planb.utils


class Migration(migrations.Migration):

    dependencies = [
        ('transport_rsync', '0006_config_use_donotrund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='rsync_path',
            field=models.CharField(default=planb.utils.lazysetting(name='PLANB_RSYNC_BIN'), max_length=255),
        ),
    ]
